### ISSUE TITLE
HuskHomes 3.0 Tracking Issue

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskHomes2#152]
This issue tracks planned features and changes for HuskHomes 3.0, sometime this year hopefully, when I have time.

## New features
- [x] Automatic server ID fetching
- [x] Cross-server respawning support
- [x] Add option for /tpahere to teleport players to their current position or where they stood on executing the command

## Rewrite
- [x] Refactor to use gradle build system
- [x] Multi-modularize plugin, with common, api and platform specific modules
- [x] Move packages to `net.william278.huskhomes`
- [ ] Rewrite EssentialsX migrator using EssentialsAPI, abstract migrator class
- [x] Better map integrations

## Changes
- [x] Better tracking for online players cross-server; enforce who you can tp to.
- [x] Fix Redis to be more reliable
- [ ] Move repository to WiIIiam278/HuskHomes (stop branding as HuskHomes2)

## Database
- [x] Stop using Hikari for SQLite handling (#148)
- [x] Stop using generic SQL for database operations
- [x] Use DATETIME rather than timestamp
- [x] Add column for respawn position for cross-server respawn-enabled servers

## Compatibility
- [ ] Fully compatible with HuskHomes v2.x
- [ ] Add new Placeholders (%huskhomes_tpaignored_toggle%) and update PAPI addon.

See also https://github.com/WiIIiam278/HuskHomes2/pull/179
